services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"  # Povolení HTTPS
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # Sdílený svazek pro certifikáty
      - ./certbot/www:/var/www/certbot   # Pro Let's Encrypt challenge

  # only needed for cert settings
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
